name: Python Tests

on: [push]

jobs:
  test-unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'py-install'
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - id: 'py-install-deps'
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - id: 'test-unit'
        name: Run unit tests
        run: |
          make test-unit

  test-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'py-install'
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - id: 'py-install-deps'
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - id: 'firebase-install'
        name: 'Install firebase'
        run: curl -sL https://firebase.tools | bash

      - id: 'test-integration'
        name: 'Run integration tests with Firebase emulators'
        run: |
          firebase emulators:exec -P demo-test \
            'make test-integration'